# ASP.NET Core backend for Project Mercury.
{ lib
, sources
, buildDotnetModule
, dotnet-sdk_10
, dotnet-aspnetcore_10
}:

buildDotnetModule rec {
  pname = "mercury-backend";
  version = "0.0.1";

  src = sources;
  projectFile = "webshell/webshell.csproj";

  dotnet-sdk = dotnet-sdk_10;
  dotnet-runtime = dotnet-aspnetcore_10;

  # Auto-generated by `nix build .#server.fetch-deps --impure --option sandbox false`.
  nugetDeps = ./deps.json;

  meta = with lib; {
    description = "Project Mercury auction platform backend";
    license = licenses.mit;
    platforms = platforms.linux;
  };
}
