// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiAuctionsByIdImagesByImageIdData, DeleteApiAuctionsByIdImagesByImageIdErrors, DeleteApiAuctionsByIdImagesByImageIdResponses, GetApiAuctionsByAuctionIdImagesByImageIdData, GetApiAuctionsByAuctionIdImagesByImageIdErrors, GetApiAuctionsByAuctionIdImagesByImageIdResponses, GetApiAuctionsByIdData, GetApiAuctionsByIdErrors, GetApiAuctionsByIdResponses, GetApiAuctionsData, GetApiAuctionsResponses, GetApiProfilepicturesByIdData, GetApiProfilepicturesByIdErrors, GetApiProfilepicturesByIdResponses, GetApiUserinfoMeData, GetApiUserinfoMeResponses, PatchApiAuctionsByIdData, PatchApiAuctionsByIdErrors, PatchApiAuctionsByIdResponses, PostApiAuctionsByIdBidData, PostApiAuctionsByIdBidErrors, PostApiAuctionsByIdBidResponses, PostApiAuctionsByIdCloseData, PostApiAuctionsByIdCloseErrors, PostApiAuctionsByIdCloseResponses, PostApiAuctionsByIdExtendCloseData, PostApiAuctionsByIdExtendCloseErrors, PostApiAuctionsByIdExtendCloseResponses, PostApiAuctionsByIdImagesData, PostApiAuctionsByIdImagesErrors, PostApiAuctionsByIdImagesResponses, PostApiAuctionsData, PostApiAuctionsErrors, PostApiAuctionsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new BackendClient()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class BackendClient extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<BackendClient> = new HeyApiRegistry<BackendClient>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        BackendClient.__registry.set(this, args?.key);
    }
    
    /**
     * Lists all auctions.
     */
    public getApiAuctions<ThrowOnError extends boolean = false>(options?: Options<GetApiAuctionsData, ThrowOnError>): RequestResult<GetApiAuctionsResponses, unknown, ThrowOnError> {
        return (options?.client ?? this.client).get<GetApiAuctionsResponses, unknown, ThrowOnError>({ url: '/api/auctions', ...options });
    }
    
    /**
     * Creates a new auction and returns its id.
     */
    public postApiAuctions<ThrowOnError extends boolean = false>(options: Options<PostApiAuctionsData, ThrowOnError>): RequestResult<PostApiAuctionsResponses, PostApiAuctionsErrors, ThrowOnError> {
        return (options.client ?? this.client).post<PostApiAuctionsResponses, PostApiAuctionsErrors, ThrowOnError>({
            url: '/api/auctions',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Returns a single auction by id.
     */
    public getApiAuctionsById<ThrowOnError extends boolean = false>(options: Options<GetApiAuctionsByIdData, ThrowOnError>): RequestResult<GetApiAuctionsByIdResponses, GetApiAuctionsByIdErrors, ThrowOnError> {
        return (options.client ?? this.client).get<GetApiAuctionsByIdResponses, GetApiAuctionsByIdErrors, ThrowOnError>({ url: '/api/auctions/{id}', ...options });
    }
    
    /**
     * Updates the mutable fields of an auction. Closed auctions cannot be updated.
     * The closure time is updated via a dedicated extension endpoint below.
     */
    public patchApiAuctionsById<ThrowOnError extends boolean = false>(options: Options<PatchApiAuctionsByIdData, ThrowOnError>): RequestResult<PatchApiAuctionsByIdResponses, PatchApiAuctionsByIdErrors, ThrowOnError> {
        return (options.client ?? this.client).patch<PatchApiAuctionsByIdResponses, PatchApiAuctionsByIdErrors, ThrowOnError>({
            url: '/api/auctions/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Extends the closure time of an open auction. The new closure time must be later than
     * the current one; the closure date can only be moved further out, never closer.
     */
    public postApiAuctionsByIdExtendClose<ThrowOnError extends boolean = false>(options: Options<PostApiAuctionsByIdExtendCloseData, ThrowOnError>): RequestResult<PostApiAuctionsByIdExtendCloseResponses, PostApiAuctionsByIdExtendCloseErrors, ThrowOnError> {
        return (options.client ?? this.client).post<PostApiAuctionsByIdExtendCloseResponses, PostApiAuctionsByIdExtendCloseErrors, ThrowOnError>({
            url: '/api/auctions/{id}/extend-close',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Adds new images to an existing auction.
     */
    public postApiAuctionsByIdImages<ThrowOnError extends boolean = false>(options: Options<PostApiAuctionsByIdImagesData, ThrowOnError>): RequestResult<PostApiAuctionsByIdImagesResponses, PostApiAuctionsByIdImagesErrors, ThrowOnError> {
        return (options.client ?? this.client).post<PostApiAuctionsByIdImagesResponses, PostApiAuctionsByIdImagesErrors, ThrowOnError>({
            ...formDataBodySerializer,
            url: '/api/auctions/{id}/images',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * Removes an image from an auction.
     */
    public deleteApiAuctionsByIdImagesByImageId<ThrowOnError extends boolean = false>(options: Options<DeleteApiAuctionsByIdImagesByImageIdData, ThrowOnError>): RequestResult<DeleteApiAuctionsByIdImagesByImageIdResponses, DeleteApiAuctionsByIdImagesByImageIdErrors, ThrowOnError> {
        return (options.client ?? this.client).delete<DeleteApiAuctionsByIdImagesByImageIdResponses, DeleteApiAuctionsByIdImagesByImageIdErrors, ThrowOnError>({ url: '/api/auctions/{id}/images/{imageId}', ...options });
    }
    
    /**
     * Closes an auction permanently.
     */
    public postApiAuctionsByIdClose<ThrowOnError extends boolean = false>(options: Options<PostApiAuctionsByIdCloseData, ThrowOnError>): RequestResult<PostApiAuctionsByIdCloseResponses, PostApiAuctionsByIdCloseErrors, ThrowOnError> {
        return (options.client ?? this.client).post<PostApiAuctionsByIdCloseResponses, PostApiAuctionsByIdCloseErrors, ThrowOnError>({ url: '/api/auctions/{id}/close', ...options });
    }
    
    /**
     * Places a maximum bid on an auction and returns the resulting bid state.
     */
    public postApiAuctionsByIdBid<ThrowOnError extends boolean = false>(options: Options<PostApiAuctionsByIdBidData, ThrowOnError>): RequestResult<PostApiAuctionsByIdBidResponses, PostApiAuctionsByIdBidErrors, ThrowOnError> {
        return (options.client ?? this.client).post<PostApiAuctionsByIdBidResponses, PostApiAuctionsByIdBidErrors, ThrowOnError>({
            url: '/api/auctions/{id}/bid',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Serves an auction image by id.
     */
    public getApiAuctionsByAuctionIdImagesByImageId<ThrowOnError extends boolean = false>(options: Options<GetApiAuctionsByAuctionIdImagesByImageIdData, ThrowOnError>): RequestResult<GetApiAuctionsByAuctionIdImagesByImageIdResponses, GetApiAuctionsByAuctionIdImagesByImageIdErrors, ThrowOnError> {
        return (options.client ?? this.client).get<GetApiAuctionsByAuctionIdImagesByImageIdResponses, GetApiAuctionsByAuctionIdImagesByImageIdErrors, ThrowOnError>({ url: '/api/auctions/{auctionId}/images/{imageId}', ...options });
    }
    
    /**
     * Serves a profile picture by id.
     */
    public getApiProfilepicturesById<ThrowOnError extends boolean = false>(options: Options<GetApiProfilepicturesByIdData, ThrowOnError>): RequestResult<GetApiProfilepicturesByIdResponses, GetApiProfilepicturesByIdErrors, ThrowOnError> {
        return (options.client ?? this.client).get<GetApiProfilepicturesByIdResponses, GetApiProfilepicturesByIdErrors, ThrowOnError>({ url: '/api/profilepictures/{id}', ...options });
    }
    
    /**
     * Return information about the currently signed in user.
     */
    public getApiUserinfoMe<ThrowOnError extends boolean = false>(options?: Options<GetApiUserinfoMeData, ThrowOnError>): RequestResult<GetApiUserinfoMeResponses, unknown, ThrowOnError> {
        return (options?.client ?? this.client).get<GetApiUserinfoMeResponses, unknown, ThrowOnError>({ url: '/api/userinfo/me', ...options });
    }
}
