// This file is auto-generated by @hey-api/openapi-ts

import {
	type Client,
	type ClientMeta,
	type Options as Options2,
	type RequestResult,
	type TDataShape,
	urlSearchParamsBodySerializer
} from './client';
import { client } from './client.gen';
import type {
	DeleteApiAuctionsByIdImagesByImageIdData,
	DeleteApiAuctionsByIdImagesByImageIdResponses,
	GetApiAuctionsByAuctionIdImagesByImageIdData,
	GetApiAuctionsByAuctionIdImagesByImageIdResponses,
	GetApiAuctionsByIdData,
	GetApiAuctionsByIdResponses,
	GetApiAuctionsData,
	GetApiAuctionsResponses,
	GetApiUserinfoMeData,
	GetApiUserinfoMeResponses,
	PatchApiAuctionsByIdData,
	PatchApiAuctionsByIdResponses,
	PostApiAuctionsByIdCloseData,
	PostApiAuctionsByIdCloseResponses,
	PostApiAuctionsByIdImagesData,
	PostApiAuctionsByIdImagesResponses,
	PostApiAuctionsData,
	PostApiAuctionsResponses
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
	protected client: Client;

	constructor(args?: { client?: Client }) {
		this.client = args?.client ?? client;
	}
}

class HeyApiRegistry<T> {
	private readonly defaultKey = 'default';

	private readonly instances: Map<string, T> = new Map();

	get(key?: string): T {
		const instance = this.instances.get(key ?? this.defaultKey);
		if (!instance) {
			throw new Error(
				`No SDK client found. Create one with "new BackendClient()" to fix this error.`
			);
		}
		return instance;
	}

	set(value: T, key?: string): void {
		this.instances.set(key ?? this.defaultKey, value);
	}
}

export class BackendClient extends HeyApiClient {
	public static readonly __registry: HeyApiRegistry<BackendClient> =
		new HeyApiRegistry<BackendClient>();

	constructor(args?: { client?: Client; key?: string }) {
		super(args);
		BackendClient.__registry.set(this, args?.key);
	}

	public getApiAuctions<ThrowOnError extends boolean = false>(
		options?: Options<GetApiAuctionsData, ThrowOnError>
	): RequestResult<GetApiAuctionsResponses, unknown, ThrowOnError> {
		return (options?.client ?? this.client).get<GetApiAuctionsResponses, unknown, ThrowOnError>({
			url: '/api/auctions',
			...options
		});
	}

	public postApiAuctions<ThrowOnError extends boolean = false>(
		options?: Options<PostApiAuctionsData, ThrowOnError>
	): RequestResult<PostApiAuctionsResponses, unknown, ThrowOnError> {
		return (options?.client ?? this.client).post<PostApiAuctionsResponses, unknown, ThrowOnError>({
			url: '/api/auctions',
			...options
		});
	}

	public getApiAuctionsById<ThrowOnError extends boolean = false>(
		options: Options<GetApiAuctionsByIdData, ThrowOnError>
	): RequestResult<GetApiAuctionsByIdResponses, unknown, ThrowOnError> {
		return (options.client ?? this.client).get<GetApiAuctionsByIdResponses, unknown, ThrowOnError>({
			url: '/api/auctions/{id}',
			...options
		});
	}

	public patchApiAuctionsById<ThrowOnError extends boolean = false>(
		options: Options<PatchApiAuctionsByIdData, ThrowOnError>
	): RequestResult<PatchApiAuctionsByIdResponses, unknown, ThrowOnError> {
		return (options.client ?? this.client).patch<
			PatchApiAuctionsByIdResponses,
			unknown,
			ThrowOnError
		>({
			url: '/api/auctions/{id}',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers
			}
		});
	}

	public postApiAuctionsByIdImages<ThrowOnError extends boolean = false>(
		options: Options<PostApiAuctionsByIdImagesData, ThrowOnError>
	): RequestResult<PostApiAuctionsByIdImagesResponses, unknown, ThrowOnError> {
		return (options.client ?? this.client).post<
			PostApiAuctionsByIdImagesResponses,
			unknown,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			url: '/api/auctions/{id}/images',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options.headers
			}
		});
	}

	public deleteApiAuctionsByIdImagesByImageId<ThrowOnError extends boolean = false>(
		options: Options<DeleteApiAuctionsByIdImagesByImageIdData, ThrowOnError>
	): RequestResult<DeleteApiAuctionsByIdImagesByImageIdResponses, unknown, ThrowOnError> {
		return (options.client ?? this.client).delete<
			DeleteApiAuctionsByIdImagesByImageIdResponses,
			unknown,
			ThrowOnError
		>({ url: '/api/auctions/{id}/images/{imageId}', ...options });
	}

	public postApiAuctionsByIdClose<ThrowOnError extends boolean = false>(
		options: Options<PostApiAuctionsByIdCloseData, ThrowOnError>
	): RequestResult<PostApiAuctionsByIdCloseResponses, unknown, ThrowOnError> {
		return (options.client ?? this.client).post<
			PostApiAuctionsByIdCloseResponses,
			unknown,
			ThrowOnError
		>({ url: '/api/auctions/{id}/close', ...options });
	}

	public getApiAuctionsByAuctionIdImagesByImageId<ThrowOnError extends boolean = false>(
		options: Options<GetApiAuctionsByAuctionIdImagesByImageIdData, ThrowOnError>
	): RequestResult<GetApiAuctionsByAuctionIdImagesByImageIdResponses, unknown, ThrowOnError> {
		return (options.client ?? this.client).get<
			GetApiAuctionsByAuctionIdImagesByImageIdResponses,
			unknown,
			ThrowOnError
		>({ url: '/api/auctions/{auctionId}/images/{imageId}', ...options });
	}

	/**
	 * Return information about the currently signed in user.
	 */
	public getApiUserinfoMe<ThrowOnError extends boolean = false>(
		options?: Options<GetApiUserinfoMeData, ThrowOnError>
	): RequestResult<GetApiUserinfoMeResponses, unknown, ThrowOnError> {
		return (options?.client ?? this.client).get<GetApiUserinfoMeResponses, unknown, ThrowOnError>({
			url: '/api/userinfo/me',
			...options
		});
	}
}
