// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * An object describing the current user.
 */
export type Me = {
    /**
     * The current user.
     */
    userinfo: UserInfo;
    /**
     * A boolean detailing if the current user can start and manage auctions
     */
    canStartAuctions?: boolean;
};

/**
 * An object describing a current user
 */
export type UserInfo = {
    /**
     * my user id
     */
    id: string;
    /**
     * display name
     */
    name: string;
    /**
     * Email address
     */
    email?: null | string;
    /**
     * Profile picture url
     */
    profilePictureUrl?: null | string;
};

export type GetApiUserinfoMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/userinfo/me';
};

export type GetApiUserinfoMeResponses = {
    /**
     * OK
     */
    200: Me;
};

export type GetApiUserinfoMeResponse = GetApiUserinfoMeResponses[keyof GetApiUserinfoMeResponses];
